name: Doc Update

on:
  push:
    branches: ["main"]
    paths:
      - "Docs/**"
      - "README.md"

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update Documentation
        uses: dineshsonachalam/markdown-autodocs@v1.0.7
        with:
          output_file_paths: "[./README.md, ./Docs/DependencyInjection.md, ./Docs/Routing.md, ./Docs/Middlewares.md]"
