name: Run CMake
description: "Runs CMake"
inputs:
  args:
    description: "Other arguments"
    required: false
    default: ""
  build-type:
    description: "Build type"
    required: false
    default: Release
  toolchain:
    description: "Toolchain file"
    required: false
    default: conan_toolchain.cmake
  shared-lib:
    description: "Shared lib"
    required: false
    default: "OFF"
  build-dir:
    description: "Build directory"
    required: true

runs:
  using: composite
  steps:
    - name: Configure CMake
      working-directory: ${{ inputs.library-type }}
      run: cmake .. -DCMAKE_BUILD_TYPE=${{ inputs.build-type }} -DSEVEN_BIT_DI_BUILD_SHARED:STRING="${{ inputs.shared-lib }}"  -DCMAKE_TOOLCHAIN_FILE:STRING="${{ inputs.toolchain }}" -DBUILD_TESTS:BOOL=true -DBUILD_EXAMPLES:BOOL=true ${{ inputs.args }}
      shell: pwsh

    - name: Build
      working-directory: ${{ inputs.build-dir }}
      run: cmake --build . --config ${{ inputs.build-type }}
      shell: pwsh
