name: Run CMake
description: "Runs CMake Build"
inputs:
  library-type:
    description: "Library type"
    required: false
    default: Static

runs:
  using: composite
  steps:

    - name: Configure CMake
      run: cmake -B ${{ env.BUILD_DIR }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -G ${{ env.GENERATOR }} -D_7BIT_DI_LIBRARY_TYPE=${{ inputs.library-type }} ${{ env.CMAKE_CONFIG_ARGS }}
      shell: pwsh

    - name: Build
      run: cmake --build ${{ env.BUILD_DIR }}
      shell: pwsh
