name: Run CMake
description: "Runs CMake Build"
inputs:
  library-type:
    description: "Library type"
    required: false
    default: Static
  build-type:
    description: "build type"
    required: true
  args:
    description: "Other arguments"
    required: false
    default: -D_7BIT_DI_BUILD_TESTS:BOOL=ON -D_7BIT_DI_BUILD_EXAMPLES:BOOL=ON


runs:
  using: composite
  steps:

    - name: Configure CMake
      working-directory: ${{ inputs.build-dir }}
      run: cmake .. -DCMAKE_BUILD_TYPE=${{ inputs.build-type }} -D_7BIT_DI_LIBRARY_TYPE=${{ inputs.library-type }} ${{ inputs.args }}
      shell: pwsh

    - name: Build
      working-directory: ${{ inputs.build-dir }}
      run: cmake --build . --config ${{ inputs.build-type }}
      shell: pwsh
