name: Run CMake
description: "Runs CMake Build"
inputs:
  library-type:
    description: "Library type"
    required: false
    default: Static
  build-type:
    description: "build type"
    required: true
  build-dir:
    description: "build directory"
    required: true
  args:
    description: "Other arguments"
    required: false
    default: -D_7BIT_DI_BUILD_TESTS:BOOL=ON -D_7BIT_DI_BUILD_EXAMPLES:BOOL=ON


runs:
  using: composite
  steps:

    - name: Configure CMake
      run: cmake -B ${{ env.BUILD_DIR }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -G ${{ env.GENERATOR }} -D_7BIT_DI_LIBRARY_TYPE=${{ inputs.library-type }} ${{ env.CMAKE_CONFIG_ARGS }}
      shell: pwsh

    - name: Build
      run: cmake --build ${{ env.BUILD_DIR }}
      shell: pwsh
