name: Setup MinGw
description: "Sets up the compiler"
inputs:
  version:
    description: "MinGw version"
    required: true

runs:
  using: composite

  steps:
    - name: Install MinGW
      run: choco install mingw --version ${{ inputs.version }} -y && choco install ninja -y
      shell: pwsh

    - name: Set Ninja
      run: echo "GENERATOR=Ninja" >> $GITHUB_ENV
      shell: bash

    - name: Set CC/CXX
      run: echo "CC=gcc" >> $GITHUB_ENV && echo "CXX=g++" >> $GITHUB_ENV
      shell: bash

    - name: Update Sys Path
      run: |
        ("C:\\ProgramData\\chocolatey\\lib\\mingw\\tools\\install\\mingw64\\bin;" + (Get-Content -Path $env:GITHUB_PATH)) | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8
      shell: pwsh
