name: Setup Compiler
description: "Sets up the compiler"
inputs:
  version:
    description: "Gcc version"
    required: true

runs:
  using: composite

  steps:
    - name: Update Environment
      uses: kanga333/variable-mapper@v0.3.0
      with:
        key: "${{ runner.os }}"
        map: |
          {
            "Windows":{
                "CC": "gcc",
                "CXX": "g++"
            }
          }

    - name: Update Sys Path
      run: refreshenv
      shell: pwsh

    - name: Install MinGW
      run: choco install mingw --version ${{ inputs.version }} -y
      shell: pwsh
