name: Setup Compiler
description: "Sets up the compiler"
inputs:
  version:
    description: "Gcc version"
    required: true

runs:
  using: composite

  steps:
    - name: Update Environment
      uses: kanga333/variable-mapper@v0.3.0
      with:
        key: "${{ runner.os }}"
        map: |
          {
            "Windows":{
                "CC": "gcc",
                "CXX": "g++"
            }
          }

    - name: Update Sys Path
      run: |
        ("C:\\ProgramData\\chocolatey\\lib\\mingw\\tools\\install\\mingw64\\bin;" + Get-Content -Path $env:GITHUB_PATH) | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      shell: pwsh

    - name: Install MinGW
      run: choco install mingw --version ${{ inputs.version }} -y
      shell: pwsh
