name: Setup Compiler
description: "Sets up the compiler"
inputs:
  version:
    description: "Gcc version"
    required: true

runs:
  using: composite
  steps:
    - name: Set Proper Conan Profile
      uses: kanga333/variable-mapper@v0.3.0
      with:
        key: "${{ runner.os }}"
        map: |
          {
            "Linux":{
                "install-gcc": "sudo apt install gcc-${{ inputs.version }} g++-${{ inputs.version }} -y",
                "CC": "gcc-${{ inputs.version }}",
                "CXX": "g++-${{ inputs.version }}"
            },
            "macOS":{
                "install-gcc": "brew install gcc@${{ inputs.version }}",
                "CC": "gcc-${{ inputs.version }}",
                "CXX": "g++-${{ inputs.version }}"
            }
          }

    - name: Install Gcc
      run: ${{ env.install-gcc }}
      shell: pwsh
