name: Setup Gcc
description: "Sets up the compiler"
inputs:
  version:
    description: "Gcc version"
    required: true

runs:
  using: composite
  steps:
    - name: Install Gcc
      if: runner.os == 'Linux'
      run: sudo apt update && sudo apt install gcc-${{ inputs.version }} g++-${{ inputs.version }} ninja-build -y
      shell: pwsh

    - name: Install Gcc
      if: runner.os == 'macOS'
      run: brew update && brew install gcc@${{ inputs.version }} ninja
      shell: pwsh

    - name: Set Ninja
      run: echo "GENERATOR=Ninja" >> $GITHUB_ENV
      shell: bash

    - name: Set CC/CXX
      run: echo "CC=gcc-${{ inputs.version }}" >> $GITHUB_ENV && echo "CXX=g++-${{ inputs.version }}" >> $GITHUB_ENV
      shell: bash
