name: Setup Clang
description: "Sets up the compiler"
inputs:
  version:
    description: "Clang version"
    required: true

runs:
  using: composite
  steps:
    - name: Set Environment
      uses: kanga333/variable-mapper@v0.3.0
      with:
        key: "${{ runner.os }}"
        map: |
          {
            "Linux":{
                "install-gcc": "sudo apt update && sudo apt install clang-${{ inputs.version }} -y",
                "CC": "clang-${{ inputs.version }}",
                "CXX": "clang++-${{ inputs.version }}"
            },
            "macOS":{
                "install-gcc": "brew update && brew install llvm@${{ inputs.version }}",
                "CC": "clang-${{ inputs.version }}",
                "CXX": "clang++-${{ inputs.version }}"
            }
          }

    - name: Install Clang
      run: ${{ env.install-gcc }}
      shell: pwsh
