name: Setup Clang
description: "Sets up the compiler"
inputs:
  version:
    description: "Clang version"
    required: true

runs:
  using: composite
  steps:
    - name: Set Environment
      uses: kanga333/variable-mapper@v0.3.0
      with:
        key: "${{ runner.os }}"
        map: |
          {
            "Linux":{
                "install-clang": "sudo apt update && sudo apt install clang-${{ inputs.version }} -y"
            },
            "macOS":{
                "install-clang": "brew update && brew install llvm@${{ inputs.version }}"
            },
            "Windows":{
                "install-clang": "choco install LLVM --version ${{ inputs.version }} --allow-downgrade -y"
            }
          }

    - name: Install Clang
      if: runner.os == 'Windows'
      run: choco install LLVM --version ${{ inputs.version }} --allow-downgrade -y
      shell: pwsh

    - name: Install Clang
      if: runner.os == 'macOS'
      run: brew update && brew install llvm@${{ inputs.version }}
      shell: pwsh

    - name: Install Clang
      if: runner.os == 'Linux'
      run: sudo apt update && sudo apt install clang-${{ inputs.version }} -y
      shell: pwsh

    - name: Set CC
      if: runner.os == 'Windows'
      run: echo "CC=clang CXX=clang++ GENERATOR=Ninja MAKE_PROGRAM=ninja" >> $GITHUB_ENV
      shell: bash

    - name: Set CC
      if: runner.os != 'Windows'
      run: echo "CC=clang-${{ inputs.version }} CXX=clang++-${{ inputs.version }} GENERATOR=Ninja MAKE_PROGRAM=ninja" >> $GITHUB_ENV
      shell: bash

    - name: Update Sys Path
      if: runner.os == 'Windows'
      run: |
        (" C:\\Program Files\\LLVM\\bin;" + (Get-Content -Path $env:GITHUB_PATH)) | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8
      shell: pwsh
