name: Setup Clang
description: "Sets up the compiler"
inputs:
  version:
    description: "Clang version"
    required: true

runs:
  using: composite
  steps:
    - name: Set Environment
      uses: kanga333/variable-mapper@v0.3.0
      with:
        key: "${{ runner.os }}"
        map: |
          {
            "Linux":{
                "install-clang": "sudo apt update && sudo apt install clang-${{ inputs.version }} -y",
                "CC": "clang-${{ inputs.version }}",
                "CXX": "clang++-${{ inputs.version }}"
            },
            "macOS":{
                "install-clang": "brew update && brew install llvm@${{ inputs.version }}",
                "CC": "clang-${{ inputs.version }}",
                "CXX": "clang++-${{ inputs.version }}"
            },
            "Windows":{
                "install-clang": "choco install LLVM --version ${{ inputs.version }} --allow-downgrade -y",
                "CC": "clang",
                "CXX": "clang++"
            }
          }

    - name: Install Clang
      run: ${{ env.install-clang }}
      shell: pwsh

    - uses: rishabhgupta/split-by@v1
      id: split
      with:
        string: ${{ inputs.version }}
        split-by: '.'

    - name: Set Environment
      uses: kanga333/variable-mapper@v0.3.0
      with:
        key: "${{ runner.os }}"
        map: |
          {
            "*":{
                "CC": "clang-${{ steps.split.outputs._1 }}",
                "CXX": "clang++-${{ steps.split.outputs._1 }}"
            }
          }
