name: Setup Clang
description: "Sets up the compiler"
inputs:
  version:
    description: "Clang version"
    required: true

runs:
  using: composite
  steps:
    - name: Set Environment
      uses: kanga333/variable-mapper@v0.3.0
      with:
        key: "${{ runner.os }}"
        map: |
          {
            "Linux":{
                "install-clang": "sudo apt update && sudo apt install clang-${{ inputs.version }} -y"
            },
            "macOS":{
                "install-clang": "brew update && brew install llvm@${{ inputs.version }}"
            },
            "Windows":{
                "install-clang": "choco install LLVM --version ${{ inputs.version }} --allow-downgrade -y"
            }
          }

    - name: Install Clang
      if: runner.os == 'Windows'
      run: choco install LLVM --version ${{ inputs.version }} --allow-downgrade -y
      shell: pwsh

    - uses: rishabhgupta/split-by@v1
      id: split
      with:
        string: ${{ inputs.version }}
        split-by: '.'

    - name: Set CC
      run: echo "CC=clang-${{ steps.split.outputs._0 }}" >> GITHUB_ENV
      shell: bash

    - name: Set CXX
      run: echo "CXX=clang++-${{ steps.split.outputs._0 }}" >> GITHUB_ENV
      shell: bash
