name: Setup Clang
description: "Sets up the compiler"
inputs:
  version:
    description: "Clang version"
    required: true

runs:
  using: composite
  steps:
    - name: Install Clang
      if: runner.os == 'Windows'
      run: choco install LLVM --version ${{ inputs.version }} --allow-downgrade -y && choco install ninja -y
      shell: pwsh

    - name: Install Clang
      if: runner.os == 'Linux'
      run: sudo apt update && sudo apt install clang-${{ inputs.version }} ninja-build -y
      shell: pwsh

    - name: Set Ninja
      run: echo "GENERATOR=Ninja" >> $GITHUB_ENV
      shell: bash

    - name: Set CC/CXX
      if: runner.os == 'Windows'
      run: echo "CC=clang" >> $GITHUB_ENV && echo "CXX=clang++" >> $GITHUB_ENV
      shell: bash

    - name: Set CC/CXX
      if: runner.os != 'Windows'
      run: echo "CC=clang-${{ inputs.version }}" >> $GITHUB_ENV && echo "CXX=clang++-${{ inputs.version }}" >> $GITHUB_ENV
      shell: bash
