name: Run CMake
description: "Runs CMake"
inputs:
  install-dir:
    description: "Installation directory"
    required: true

runs:
  using: composite
  steps:
    - name: Install Conan
      uses: turtlebrowser/get-conan@main

    - name: Configure Conan
      run: conan profile detect
      shell: pwsh

    - name: Install Conan Packages in ${{ inputs.install-dir }}
      run: conan install . --output-folder=${{ inputs.install-dir }} --build=missing
      shell: pwsh
