name: CI

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-12, windows-2022]

    runs-on: ${{matrix.os}}

    steps:
      - name: Check CMake 3.5
        uses: ./.github/actions/CMakeTest
        with:
          cmake-version: "3.15"
          library-type: "Static"
