name: BasicTest

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

env:
  BUILD_TYPE: Release
  BUILD_DIR: ${{github.workspace}}/build

jobs:
  test-posix:
    strategy:
      fail-fast: false
      matrix:
        libraryType: [HeaderOnly, Static]
        os: [ubuntu-22.04, macos-12, windows-2022]

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v3

      - name: Install Conan
        uses: turtlebrowser/get-conan@main

      - name: Configure Conan
        run: conan profile detect

      - name: Install Conan Packages
        run: conan install . --output-folder=${{ env.BUILD_DIR }} --build=missing

      - name: Configure CMake
        working-directory: ${{ env.BUILD_DIR }}
        run: cmake .. -DLIBRARY_TYPE=${{ matrix.libraryType }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DBUILD_TESTS:BOOL=true -DBUILD_EXAMPLES:BOOL=true -DCMAKE_TOOLCHAIN_FILE:STRING="conan_toolchain.cmake"

      - name: Build
        working-directory: ${{ env.BUILD_DIR }}
        run: cmake --build . --config ${{ env.BUILD_TYPE }}

      - name: Test
        working-directory: ${{ env.BUILD_DIR }}
        run: ctest -C ${{env.BUILD_TYPE}}
