name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  BUILD_TYPE: Release
  BUILD_FLAGS: -DBUILD_TESTS:BOOL=true -DBUILD_EXAMPLES:BOOL=true -DCMAKE_TOOLCHAIN_FILE:STRING="conan_toolchain.cmake"
  BUILD_DIR: ${{github.workspace}}/build

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        libraryType: [HeaderOnly, Static]
        os:
          [
            ubuntu-20.04,
            ubuntu-22.04,
            macos-11,
            macos-12,
            windows-2019,
            windows-2022,
          ]

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v3

      - name: Install Conan
        uses: turtlebrowser/get-conan@main

      - name: Configure Conan
        run: conan profile detect

      - name: Install Conan Packages
        run: conan install . --output-folder=${{ env.BUILD_DIR }} --build=missing

      - name: Configure CMake
        working-directory: ${{ env.BUILD_DIR }}
        run: cmake .. ${{ env.BUILD_FLAGS }} -DLIBRARY_TYPE=${{ matrix.libraryType }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build
        working-directory: ${{ env.BUILD_DIR }}
        run: cmake --build . --config ${{ env.BUILD_TYPE }}

      - name: Test
        working-directory: ${{ env.BUILD_DIR }}
        run: ctest -C ${{env.BUILD_TYPE}}
