name: DevCI

on:
  push:
    branches: ["dev"]
    paths-ignore:
      - "Docs/**"
      - ".readthedocs.yaml"
      - "README.md"

env:
  BUILD_TYPE: Release
  BUILD_DIR: ${{github.workspace}}/build

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        libraryType: [HeaderOnly, Static, Shared]
        os: [ubuntu-22.04, macos-12, windows-2022]

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v3

      - name: Install Conan Packages
        uses: ./.github/actions/conan-install
        with:
          install-dir: ${{ env.BUILD_DIR }}

      - name: CMake Build
        uses: ./.github/actions/cmake-build
        with:
          library-type: ${{ matrix.libraryType }}

      - name: Test
        run: ctest -j 10 --preset conan-release
