name: Linux

on:
  push:
    branches: [ "dev" ]
    paths-ignore:
      - "Docs/**"
      - ".readthedocs.yaml"
      - "README.md"

  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "Docs/**"
      - ".readthedocs.yaml"
      - "README.md"

permissions:
  contents: read

env:
  BUILD_DIR: ${{github.workspace}}/build

jobs:
  test:
    strategy:
      matrix:
        compiler: [
          { tool: g++, ver: 7 },
          { tool: g++, ver: 8 },
          { tool: g++, ver: 9 },
          { tool: g++, ver: 10 },
          { tool: g++, ver: 11 },
          { tool: g++, ver: 12 },
          { tool: g++, ver: 13 },
          { tool: clang, ver: 7 },
          { tool: clang, ver: 8 },
          { tool: clang, ver: 9 },
          { tool: clang, ver: 10 },
          { tool: clang, ver: 11 },
          { tool: clang, ver: 12 },
          { tool: clang, ver: 13 },
          { tool: clang, ver: 14 },
          { tool: clang, ver: 15 } ]
        build_type: [ Release ]
        os: [ ubuntu-20.04, ubuntu-22.04 ]
        std: [ 17, 20 ]
        library_type: [ Static ]
        include:
          - compiler: { tool: g++, cxx: g++ }
          - compiler: { tool: clang, cxx: clang++ }
        exclude:
          - { os: ubuntu-20.04, compiler: { tool: g++, ver: 12 } }
          - { os: ubuntu-20.04, compiler: { tool: g++, ver: 13 } }
          - { os: ubuntu-20.04, compiler: { tool: clang, ver: 13 } }
          - { os: ubuntu-20.04, compiler: { tool: clang, ver: 14 } }
          - { os: ubuntu-20.04, compiler: { tool: clang, ver: 15 } }
          - { os: ubuntu-22.04, compiler: { tool: g++, ver: 7 } }
          - { os: ubuntu-22.04, compiler: { tool: g++, ver: 8 } }
          - { os: ubuntu-22.04, compiler: { tool: clang, ver: 7 } }
          - { os: ubuntu-22.04, compiler: { tool: clang, ver: 8 } }
          - { os: ubuntu-22.04, compiler: { tool: clang, ver: 9 } }
          - { os: ubuntu-22.04, compiler: { tool: clang, ver: 10 } }

    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3

      - name: Create Build Environment
        run: |
          sudo apt update
          sudo apt install ${{matrix.compiler.tool}}-${{matrix.compiler.ver}} -y
          sudo apt install locales-all
          echo "CXX=${{matrix.compiler.cxx}}-${{matrix.compiler.ver}}" >> $GITHUB_ENV 

      - name: Configure
        run: |
          cmake -B ${{env.BUILD_DIR}} -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_STANDARD=${{matrix.std}} \
                -DCMAKE_CXX_VISIBILITY_PRESET=hidden -DCMAKE_VISIBILITY_INLINES_HIDDEN=ON \
                -D_7BIT_DI_LIBRARY_TYPE=${{matrix.library_type}} -D_7BIT_DI_BUILD_TESTS=ON \

      - name: Build
        run: |
          threads=`nproc`
          cmake --build ${{env.BUILD_DIR}} --config ${{matrix.build_type}} --parallel $threads

      - name: Test
        working-directory: ${{env.BUILD_DIR}}
        run: ctest -C ${{matrix.build_type}}
        env:
          CTEST_OUTPUT_ON_FAILURE: True
