name: Linux

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "Docs/**"
      - ".readthedocs.yaml"
      - "README.md"

jobs:
  test:
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        compiler:
          - { name: GCC, ver: 7 }
          - { name: GCC, ver: 8 }
          - { name: GCC, ver: 9 }
          - { name: GCC, ver: 10 }
          - { name: GCC, ver: 11 }
          - { name: GCC, ver: 12 }
          - { name: GCC, ver: 13 }
          - { name: GCC, ver: 14 }
          - { name: Clang, ver: 7 }
          - { name: Clang, ver: 8 }
          - { name: Clang, ver: 9 }
          - { name: Clang, ver: 10 }
          - { name: Clang, ver: 11 }
          - { name: Clang, ver: 12 }
          - { name: Clang, ver: 13 }
          - { name: Clang, ver: 14 }
          - { name: Clang, ver: 15 }
          - { name: Clang, ver: 16 }
          - { name: Clang, ver: 17 }
          - { name: Clang, ver: 18 }
        build_type: [ Release ]
        os: [ ubuntu-20.04, ubuntu-22.04, ubuntu-24.04 ]
        std: [ 17, 20, 23 ]
        library_type: [ Static ]
        include:
          - compiler: { name: GCC }
            cxx: g++
            cc: gcc
            packages: 'gcc-{0} g++-{0}'
            generator: Ninja
          - compiler: { name: Clang }
            cxx: clang++
            cc: clang
            packages: 'clang-{0}'
            generator: Ninja
        exclude:
          - { os: ubuntu-20.04, compiler: { name: GCC, ver: 11 } }
          - { os: ubuntu-20.04, compiler: { name: GCC, ver: 12 } }
          - { os: ubuntu-20.04, compiler: { name: GCC, ver: 13 } }
          - { os: ubuntu-20.04, compiler: { name: GCC, ver: 14 } }
          - { os: ubuntu-20.04, compiler: { name: Clang, ver: 13 } }
          - { os: ubuntu-20.04, compiler: { name: Clang, ver: 14 } }
          - { os: ubuntu-20.04, compiler: { name: Clang, ver: 15 } }
          - { os: ubuntu-20.04, compiler: { name: Clang, ver: 16 } }
          - { os: ubuntu-20.04, compiler: { name: Clang, ver: 17 } }
          - { os: ubuntu-20.04, compiler: { name: Clang, ver: 18 } }
          - { os: ubuntu-22.04, compiler: { name: GCC, ver: 7 } }
          - { os: ubuntu-22.04, compiler: { name: GCC, ver: 8 } }
          - { os: ubuntu-22.04, compiler: { name: GCC, ver: 13 } }
          - { os: ubuntu-22.04, compiler: { name: GCC, ver: 14 } }
          - { os: ubuntu-22.04, compiler: { name: Clang, ver: 7 } }
          - { os: ubuntu-22.04, compiler: { name: Clang, ver: 8 } }
          - { os: ubuntu-22.04, compiler: { name: Clang, ver: 9 } }
          - { os: ubuntu-22.04, compiler: { name: Clang, ver: 10 } }
          - { os: ubuntu-22.04, compiler: { name: Clang, ver: 16 } }
          - { os: ubuntu-22.04, compiler: { name: Clang, ver: 17 } }
          - { os: ubuntu-22.04, compiler: { name: Clang, ver: 18 } }
          - { os: ubuntu-24.04, compiler: { name: GCC, ver: 7 } }
          - { os: ubuntu-24.04, compiler: { name: GCC, ver: 8 } }
          - { os: ubuntu-24.04, compiler: { name: Clang, ver: 7 } }
          - { os: ubuntu-24.04, compiler: { name: Clang, ver: 8 } }
          - { os: ubuntu-24.04, compiler: { name: Clang, ver: 9 } }
          - { os: ubuntu-24.04, compiler: { name: Clang, ver: 10 } }
          - { os: ubuntu-24.04, compiler: { name: Clang, ver: 11 } }
          - { os: ubuntu-24.04, compiler: { name: Clang, ver: 12 } }
          - { os: ubuntu-24.04, compiler: { name: Clang, ver: 13 } }
          - { compiler: { name: GCC, ver: 7 }, std: 20 }
          - { compiler: { name: GCC, ver: 7 }, std: 23 }
          - { compiler: { name: GCC, ver: 8 }, std: 23 }
          - { compiler: { name: GCC, ver: 9 }, std: 23 }
          - { compiler: { name: GCC, ver: 10 }, std: 23 }
          - { compiler: { name: Clang, ver: 7 }, std: 20 }
          - { compiler: { name: Clang, ver: 7 }, std: 23 }
          - { compiler: { name: Clang, ver: 8 }, std: 20 }
          - { compiler: { name: Clang, ver: 8 }, std: 23 }
          - { compiler: { name: Clang, ver: 9 }, std: 23 }
          - { compiler: { name: Clang, ver: 10 }, std: 23 }
          - { compiler: { name: Clang, ver: 11 }, std: 23 }
          - { os: ubuntu-24.04, compiler: { name: Clang, ver: 14 }, std: 20 } # gtest broken for now
          - { os: ubuntu-24.04, compiler: { name: Clang, ver: 14 }, std: 23 } # gtest broken for now
          - { os: ubuntu-24.04, compiler: { name: Clang, ver: 15 }, std: 20 } # gtest broken for now
          - { os: ubuntu-24.04, compiler: { name: Clang, ver: 15 }, std: 23 } # gtest broken for now
          - { os: ubuntu-24.04, compiler: { name: Clang, ver: 17 }, std: 23 } # gtest broken for now

    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4

      - name: Create Build Environment
        run: |
          sudo apt update
          sudo apt install ${{format(matrix.packages, matrix.compiler.ver)}} ninja-build -y
          sudo apt install locales-all
          cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure
        env:
          CXX: ${{matrix.cxx}}-${{matrix.compiler.ver}}
          CC: ${{matrix.cc}}-${{matrix.compiler.ver}}
        run: cmake -B ${{runner.workspace}}/build -G "${{matrix.generator}}" -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_STANDARD=${{matrix.std}} -D_7BIT_DI_LIBRARY_TYPE=${{matrix.library_type}} -D_7BIT_DI_BUILD_ALL_TESTS=ON

      - name: Build
        run: cmake --build ${{runner.workspace}}/build --config ${{matrix.build_type}} -j

      - name: Test
        working-directory: ${{runner.workspace}}/build
        run: ctest -C ${{matrix.build_type}} --output-on-failure
