name: MacOs

on:
  push:
    branches: [ "dev" ]
    paths-ignore:
      - "Docs/**"
      - ".readthedocs.yaml"
      - "README.md"

  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "Docs/**"
      - ".readthedocs.yaml"
      - "README.md"

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        compiler:
          - { tool: apple-clang },
          - { tool: gcc, ver: 9 },
          - { tool: gcc, ver: 10 },
          - { tool: gcc, ver: 11 },
          - { tool: gcc, ver: 12 },
          - { tool: gcc, ver: 13 }
        build_type: [ Release ]
        os: [ macos-12, macos-13 ]
        std: [ 17, 20 ]
        library_type: [ Static ]
        include:
          - compiler: { tool: gcc, cxx: g++ }

    env:
      BUILD_DIR: ${{github.workspace}}/build

    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3

      - name: Create Build Environment
        if: matrix.compiler.cpp != 'apple-clang'
        run: |
          brew update
          brew install ${{matrix.compiler.tool}}@${{matrix.compiler.ver}} 
          echo "CXX=${{matrix.compiler.cxx}}-${{matrix.compiler.ver}}" >> $GITHUB_ENV 

      - name: Configure
        run: |
          cmake -B ${{env.BUILD_DIR}} -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_STANDARD=${{matrix.std}} \
                -DCMAKE_CXX_VISIBILITY_PRESET=hidden -DCMAKE_VISIBILITY_INLINES_HIDDEN=ON \
                -D_7BIT_DI_LIBRARY_TYPE=${{matrix.library_type}} -D_7BIT_DI_BUILD_TESTS=ON \

      - name: Build
        run: |
          threads=`sysctl -n hw.logicalcpu`
          cmake --build ${{env.BUILD_DIR}} --config ${{matrix.build_type}} --parallel $threads

      - name: Test
        working-directory: ${{env.BUILD_DIR}}
        run: ctest -C ${{matrix.build_type}}
        env:
          CTEST_OUTPUT_ON_FAILURE: True
