name: MacOs

on:
  push:
    branches: [ "dev" ]
    paths-ignore:
      - "Docs/**"
      - ".readthedocs.yaml"
      - "README.md"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "Docs/**"
      - ".readthedocs.yaml"
      - "README.md"

jobs:
  test:
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        compiler: [
          { tool: llvm, ver: 12 },
          { tool: llvm, ver: 13 },
          { tool: llvm, ver: 14 },
          { tool: llvm, ver: 15 },
          { tool: llvm, ver: 16 },
          { tool: llvm, ver: 17 },
          { tool: llvm, ver: 18 } ]
        build_type: [ Release ]
        os: [ macos-12, macos-13, macos-14 ]
        std: [ 17, 20, 23 ]
        library_type: [ Static ]
        include:
          - compiler: { tool: llvm }
            cxx: clang++
            cc: clang

    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4

      - name: Create Build Environment
        if: matrix.compiler.tool != 'apple-clang'
        run: |
          brew upgrade &&
          brew install ${{matrix.compiler.tool}}@${{matrix.compiler.ver}} ninja
          cmake -E make_directory ${{runner.workspace}}/build

      - name: Setup Environment
        if: matrix.compiler.tool == 'llvm'
        run: |
          echo "CXX=/opt/homebrew/opt/llvm@${{matrix.compiler.ver}}/bin/${{matrix.cxx}}" >> $GITHUB_ENV
          echo "CC=/opt/homebrew/opt/llvm@${{matrix.compiler.ver}}/bin/${{matrix.cc}}" >> $GITHUB_ENV

      - name: Setup Environment
        if: matrix.compiler.tool == 'gcc'
        run: |
          echo "CXX=${{matrix.cxx}}" >> $GITHUB_ENV
          echo "CC=${{matrix.cc}}" >> $GITHUB_ENV

      - name: Configure
        run: cmake -B ${{runner.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_STANDARD=${{matrix.std}} -D_7BIT_DI_LIBRARY_TYPE=${{matrix.library_type}} -D_7BIT_DI_BUILD_ALL_TESTS=ON

      - name: Build
        run: cmake --build ${{runner.workspace}}/build --config ${{matrix.build_type}} -j

      - name: Test
        working-directory: ${{runner.workspace}}/build
        run: ctest -C ${{matrix.build_type}} --output-on-failure
