name: MacOs

on:
  push:
    branches: [ "dev" ]
    paths-ignore:
      - "Docs/**"
      - ".readthedocs.yaml"
      - "README.md"

  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "Docs/**"
      - ".readthedocs.yaml"
      - "README.md"

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        cpp: [ default ,g++-9 ,g++-10 ,g++-11 ,g++-12 ,g++-13 ]

        build_type: [ Release ]
        os: [ macos-11, macos-12, macos-13 ]
        std: [ 17, 20 ]
        exclude:
          - { os: macos-11, std: 20 }
          - { os: macos-13, std: 11 }
          - { os: macos-13, std: 17 }
          - { os: macos-12, cpp: g++-9 }

    env:
      BUILD_DIR: ${{github.workspace}}/build

    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3

      - name: Create Build Environment
        if: matrix.cpp != 'default'
        run: |
          sudo apt update
          sudo apt install ${{matrix.cpp}}
          sudo apt install locales-all
          cmake -E make_directory ${{env.BUILD_DIR}}

      - name: Configure
        env:
          CXX: ${{matrix.cpp}}
        run: |
          cmake -B ${{env.BUILD_DIR}} -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -D_7BIT_DI_LIBRARY_TYPE=Static \
                -DCMAKE_CXX_STANDARD=${{matrix.std}} -D_7BIT_DI_BUILD_TESTS=ON \
                -DCMAKE_CXX_VISIBILITY_PRESET=hidden -DCMAKE_VISIBILITY_INLINES_HIDDEN=ON \

      - name: Build
        run: |
          threads=`sysctl -n hw.logicalcpu`
          cmake --build ${{env.BUILD_DIR}} --config ${{matrix.build_type}} --parallel $threads

      - name: Test
        working-directory: ${{env.BUILD_DIR}}
        run: ctest -C ${{matrix.build_type}}
        env:
          CTEST_OUTPUT_ON_FAILURE: True
