name: MacOs

on:
  push:
    branches: [ "dev" ]
    paths-ignore:
      - "Docs/**"
      - ".readthedocs.yaml"
      - "README.md"

  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "Docs/**"
      - ".readthedocs.yaml"
      - "README.md"

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        compiler: [
          { cpp: apple-clang, cxx: clang },
          { cpp: gcc@9, cxx: g++-9 },
          { cpp: gcc@10, cxx: g++-10 },
          { cpp: gcc@11, cxx: g++-11 },
          { cpp: gcc@12, cxx: g++-12 },
          { cpp: gcc@13, cxx: g++-13 }
        ]
        build_type: [ Release ]
        os: [ macos-11, macos-12, macos-13 ]
        std: [ 17, 20 ]
        exclude:
          - { os: macos-11, std: 20 }
          - { os: macos-13, std: 17 }
          - { os: macos-12, compiler: { cpp: gcc@9 } }
          - { os: macos-13, compiler: { cpp: gcc@9 } }

    env:
      BUILD_DIR: ${{github.workspace}}/build

    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3

      - name: Create Build Environment
        if: matrix.compiler.cpp != 'apple-clang'
        run: |
          brew update
          brew install ${{ matrix.compiler.cpp }} 
          cmake -E make_directory ${{env.BUILD_DIR}}
          echo "CXX=${{matrix.compiler.cxx}}" >> $GITHUB_ENV 

      - name: Configure
        run: |
          cmake -B ${{env.BUILD_DIR}} -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -D_7BIT_DI_LIBRARY_TYPE=Static \
                -DCMAKE_CXX_STANDARD=${{matrix.std}} -D_7BIT_DI_BUILD_TESTS=ON \
                -DCMAKE_CXX_VISIBILITY_PRESET=hidden -DCMAKE_VISIBILITY_INLINES_HIDDEN=ON \

      - name: Build
        run: |
          threads=`sysctl -n hw.logicalcpu`
          cmake --build ${{env.BUILD_DIR}} --config ${{matrix.build_type}} --parallel $threads

      - name: Test
        working-directory: ${{env.BUILD_DIR}}
        run: ctest -C ${{matrix.build_type}}
        env:
          CTEST_OUTPUT_ON_FAILURE: True
