name: MainCI

on:
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "Docs/**"
      - ".readthedocs.yaml"
      - "README.md"

env:
  BUILD_TYPE: Release
  BUILD_DIR: ${{github.workspace}}/build

jobs:
  test-gcc:
    strategy:
      matrix:
        libraryType: [Static]
        version: [7, 8, 10, 11]
        os: [ubuntu-20.04]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Install GCC
        uses: egor-tensin/setup-gcc@v1.3
        with:
          version: ${{ matrix.version }}

      - name: Install Conan Packages
        uses: ./.github/actions/conan-install
        with:
          install-dir: ${{ env.BUILD_DIR }}

      - name: CMake Build
        uses: ./.github/actions/cmake-build
        with:
          build-dir: ${{ env.BUILD_DIR }}
          build-type: ${{ env.BUILD_TYPE }}

      - name: Test
        working-directory: ${{ env.BUILD_DIR }}
        run: ctest -C ${{env.BUILD_TYPE}}

  test-clang:
    strategy:
      matrix:
        libraryType: [Static]
        version: [6, 13, 14, 15]
        os: [ubuntu-20.04]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Install Clang
        uses: egor-tensin/setup-clang@v1.4
        with:
          version: ${{ matrix.version }}

      - name: Install Conan Packages
        uses: ./.github/actions/conan-install
        with:
          install-dir: ${{ env.BUILD_DIR }}

      - name: CMake Build
        uses: ./.github/actions/cmake-build
        with:
          build-dir: ${{ env.BUILD_DIR }}
          build-type: ${{ env.BUILD_TYPE }}

      - name: Test
        working-directory: ${{ env.BUILD_DIR }}
        run: ctest -C ${{env.BUILD_TYPE}}
