name: MainCI

on:
  push:
    branches: ["dev"]
    paths-ignore:
      - "Docs/**"
      - ".readthedocs.yaml"
      - "Readme.md"
  pull_request:
    branches: ["dev"]
    paths-ignore:
      - "Docs/**"
      - ".readthedocs.yaml"
      - "Readme.md"

env:
  BUILD_TYPE: Release
  BUILD_DIR: ${{github.workspace}}/build

jobs:
  test-gcc:
    strategy:
      matrix:
        libraryType: [HeaderOnly, Static, Shared]
        version: [7, 10, 12]
        os: [ubuntu-22.04]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Install GCC
        uses: egor-tensin/setup-gcc@v1.3
        with:
          version: ${{ matrix.version }}

      - name: Install Conan Packages
        uses: ./.github/actions/conan-install
        with:
          install-dir: ${{ env.BUILD_DIR }}

      - name: CMake Build
        uses: ./.github/actions/cmake-build
        with:
          build-dir: ${{ env.BUILD_DIR }}
          build-type: ${{ env.BUILD_TYPE }}

      - name: Test
        working-directory: ${{ env.BUILD_DIR }}
        run: ctest -C ${{env.BUILD_TYPE}}

  test-mingw:
    strategy:
      matrix:
        libraryType: [HeaderOnly, Static]
        version: [7, 10, 12]
        os: [windows-2022]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Install MinGW
        uses: egor-tensin/setup-mingw@v2.2.0
        with:
          version: ${{ matrix.version }}

      - name: Install Conan Packages
        uses: ./.github/actions/conan-install
        with:
          install-dir: ${{ env.BUILD_DIR }}

      - name: CMake Build
        uses: ./.github/actions/cmake-build
        with:
          build-dir: ${{ env.BUILD_DIR }}
          build-type: ${{ env.BUILD_TYPE }}

      - name: Test
        working-directory: ${{ env.BUILD_DIR }}
        run: ctest -C ${{env.BUILD_TYPE}}

  test-clang:
    strategy:
      matrix:
        libraryType: [HeaderOnly, Static]
        version: [6, 10, 15]
        os: [windows-2022, ubuntu-22.04]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Install Clang
        uses: egor-tensin/setup-clang@v1.4
        with:
          version: ${{ matrix.version }}

      - name: Install Conan Packages
        uses: ./.github/actions/conan-install
        with:
          install-dir: ${{ env.BUILD_DIR }}

      - name: CMake Build
        uses: ./.github/actions/cmake-build
        with:
          build-dir: ${{ env.BUILD_DIR }}
          build-type: ${{ env.BUILD_TYPE }}

      - name: Test
        working-directory: ${{ env.BUILD_DIR }}
        run: ctest -C ${{env.BUILD_TYPE}}

  test-msvc:
    strategy:
      fail-fast: false
      matrix:
        libraryType: [HeaderOnly, Static]
        version: [14, 15, 17]
        os: [windows-2022]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Install MSVC
        uses: TheMrMilchmann/setup-msvc-dev@v2.0.0
        with:
          toolset: ${{ matrix.version }}
          arch: x64

      - name: Install Conan Packages
        uses: ./.github/actions/conan-install
        with:
          install-dir: ${{ env.BUILD_DIR }}

      - name: CMake Build
        uses: ./.github/actions/cmake-build
        with:
          build-dir: ${{ env.BUILD_DIR }}
          build-type: ${{ env.BUILD_TYPE }}

      - name: Test
        working-directory: ${{ env.BUILD_DIR }}
        run: ctest -C ${{env.BUILD_TYPE}}
