name: MinGwCI

on:
  push:
    branches: [ "dev" ]
    paths-ignore:
      - "Docs/**"
      - ".readthedocs.yaml"
      - "README.md"

  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "Docs/**"
      - ".readthedocs.yaml"
      - "README.md"

env:
  BUILD_TYPE: Release
  BUILD_DIR: ${{github.workspace}}/build
  CMAKE_CONFIG_ARGS: -D_7BIT_DI_BUILD_TESTS:BOOL=ON -D_7BIT_DI_BUILD_EXAMPLES:BOOL=ON

jobs:
    test-mingw:
      strategy:
        matrix:
          version: [ 7.5.0, 8.5.0, 9.4.0, 10.3.0, 11.2.0, 12.2.0, 13.2.0 ]
          os: [ windows-2019, windows-2022 ]

      runs-on: ${{ matrix.os }}

      steps:
        - uses: actions/checkout@v3

        - name: Install MinGw
          uses: ./.github/actions/setup-mingw
          with:
            version: ${{ matrix.version }}

        - name: CMake Build
          uses: ./.github/actions/cmake-build

        - name: Test
          working-directory: ${{ env.BUILD_DIR }}
          run: ctest -C ${{ env.BUILD_TYPE }}
